stages:
    - build
    - unit_tests

build:
    image: epitechcontent/epitest-docker
    stage: build
    script:
        - make re

server_test:
    image: epitechcontent/epitest-docker
    stage: unit_tests
    script:
        - make -C library/csv/
        - make -C library/linked_list
        - make -C Server build_tests
        - ./Server/tests_run -f

graph_test:
    image: epitechcontent/epitest-docker
    stage: unit_tests
    script:
        - make -C Graphical build_tests
        - ./Graphical/tests_run -f

csv_test:
    image: epitechcontent/epitest-docker
    stage: unit_tests
    script:
        - make -C library/csv build_tests
        - ./library/csv/tests_run -f

library_test:
    image: epitechcontent/epitest-docker
    stage: unit_tests
    script:
        - make -C library/linked_list build_tests
        - ./library/linked_list/tests_run -f

covering:
    image: epitechcontent/epitest-docker
    stage: unit_tests
    script:
        - make tests_run
